#!/bin/bash
REPLACE="__REMOTE"
if [ ${#} -nq 0 ] ; then
    _args= "${@}"
    git remote | xargs -I{} sh -c "git $(echo ¥"${_args}¥" | sed -e 's/${REPLACE}/{}/g')"
else
    echo "input error"
fi

# git-sync pull __REMOTE master
# git-sync push __REMOTE master